/* Generated By:JavaCC: Do not edit this line. Lexer1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Lexer1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 29;
  /** RegularExpression Id. */
  int LETTER = 30;
  /** RegularExpression Id. */
  int ID = 31;
  /** RegularExpression Id. */
  int INTLIT = 32;
  /** RegularExpression Id. */
  int STRLIT = 33;
  /** RegularExpression Id. */
  int OPERATOR = 34;
  /** RegularExpression Id. */
  int DELIMITER = 35;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ML_COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"class\"",
    "\"extend\"",
    "\"static\"",
    "\"public\"",
    "\"void\"",
    "\"int\"",
    "\"boolean\"",
    "\"new\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"main\"",
    "\"true\"",
    "\"false\"",
    "\"String\"",
    "\"System\"",
    "\"out\"",
    "\"println\"",
    "\"this\"",
    "<DIGIT>",
    "<LETTER>",
    "<ID>",
    "<INTLIT>",
    "<STRLIT>",
    "<OPERATOR>",
    "<DELIMITER>",
  };

}
